<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.views.PasswordResetTest" tests="10" time="0.008">
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_complete" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_different_passwords" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_invalid" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_invalid_post" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_invalid_user" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_overflow_user" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_confirm_valid" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_email_found" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_email_found_custom_from" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.PasswordResetTest" name="test_email_not_found" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
